# Generated by Django 3.2.18 on 2023-04-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_pw',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_living',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
