# Generated by Django 3.2.18 on 2023-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_pw_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
