# Generated by Django 3.2.18 on 2023-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230413_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
