# Generated by Django 3.2.18 on 2023-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
